---
title: "Exercícios"
author: "William Amorim"
---

```{r, message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  eval = FALSE
)
```

## Exercícios

--------------------------------------------------------------------------------

**1.**

Reescreva a expressão abaixo utilizando o `%>%`.

```{r}
round(mean(sum(1:10)/3), digits = 1)
```

**Dica**: utilize a função `magrittr::divide_by()`. Veja o help da função para mais informações.

--------------------------------------------------------------------------------

**2.**

Reescreva o código abaixo utilizando o `%>%`.

```{r}

x <- rnorm(100)

x.pos <- x[x>0]

media <- mean(x.pos)

saida <- round(media, 1)

```


--------------------------------------------------------------------------------

**3.**

Sem rodar, diga qual a saída do código abaixo. Consulte o help das funções caso precise.

```{r}
2 %>% 
  add(2) %>% 
  c(6, NA) %>% 
  mean(na.rm = T) %>% 
  equals(5)
```


--------------------------------------------------------------------------------

**4.**

Leia o capítulo sobre *pipes* do [R for data science](http://r4ds.had.co.nz/pipes.html). É curto e vale muito a pena.

--------------------------------------------------------------------------------

**5.**

Pegue algum script que você já tenha programado em R e o reescreva utilizando o operador *pipe*. Se você não tiver nenhum, não se preocupe. Utilizaremos **bastante** o *pipe* daqui pra frente.

--------------------------------------------------------------------------------
