---
title: "Respostas"
author: "William Amorim"
---

```{r, message=FALSE, warning=FALSE, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE, 
  out.width = "60%", out.height = "60%",
  fig.retina = 2
)
```

```{r, echo = FALSE, message = FALSE, warning = FALSE}
library(magrittr)
```


## Respostas

<!-- <div class='admonition note'> -->
<!-- <p class='admonition-title'> -->
<!-- Nota -->
<!-- </p> -->
<!-- <p> -->
<!-- Não há apenas uma maneira de resolver os exercícios. Você pode encontrar soluções diferentes das nossas, algumas vezes mais eficientes, outras vezes menos. Quando estiver fazendo suas análises, tente buscar o equilíbrio entre eficiência e praticidade. Economizar 1 hora com a execução do código pode não valer a pena se você demorou 2 horas a mais para programá-lo. -->
<!-- </p> -->
<!-- </div> -->

--------------------------------------------------------------------------------

**1.**

Reescreva a expressão abaixo utilizando o `%>%`.

```{r}
round(mean(sum(1:10)/3), digits = 1)

1:10 %>% 
  sum %>% 
  divide_by(3) %>% 
  round(digits = 1)
```

--------------------------------------------------------------------------------

**2.**

Reescreva o código abaixo utilizando o `%>%`.

```{r}

# Setamos a semente que gera números aleatórios para deixar o resultado reprodutível

set.seed(137)

x <- rnorm(100)
x.pos <- x[x>0]
media <- mean(x.pos)
saida <- round(media, 2)
saida

set.seed(137)

rnorm(100) %>% 
  extract(. > 0) %>% 
  mean %>%
  round(digits = 2)

```

--------------------------------------------------------------------------------

**3.**

Sem rodar, diga qual a saída do código abaixo. Consulte o help das funções caso precise.

```{r, eval = FALSE}
2 %>% 
  add(2) %>% 
  c(6, NA) %>% 
  mean(na.rm = T) %>% 
  equals(5)
```

- Primeiro, somamos 2 com 2, gerando o valor 4.
- Então colocamos esse valor em um vetor com os valores 6 e `NA`.
- Em seguida, tiramos a média desse vetor, desconsiderando o `NA`, obtendo o valor 5.
- Por fim, testemos se o valor é igual a 5, obtendo o valor `TRUE`.

--------------------------------------------------------------------------------
